#############################################################################
# Makefile for building: comb_fit
# Generated by qmake (2.01a) (Qt 4.8.7) on: Tue Aug 21 16:34:37 2018
# Project:  combined_fit.pro
# Template: app
# Command: /usr/lib/x86_64-linux-gnu/qt4/bin/qmake -o Makefile combined_fit.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = 
CFLAGS        = -m64 -pipe -O2 -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O3 -std=c++1y -O2 -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/local/include/eigen3
LINK          = g++
LFLAGS        = -m64 -O3 -std=c++1y -Wl,-O1
LIBS          = $(SUBLIBS)   -lecf 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/x86_64-linux-gnu/qt4/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = objects/

####### Files

SOURCES       = src/RandomNumbers.cc \
		src/GaussMutOp.cc \
		src/MyFloatingPoint.cc \
		src/main.cpp \
		src/GaussianFitFunctor.cpp \
		src/EvalOp.cc \
		src/basis.cpp 
OBJECTS       = objects/RandomNumbers.o \
		objects/GaussMutOp.o \
		objects/MyFloatingPoint.o \
		objects/main.o \
		objects/GaussianFitFunctor.o \
		objects/EvalOp.o \
		objects/basis.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		combined_fit.pro
QMAKE_TARGET  = comb_fit
DESTDIR       = 
TARGET        = comb_fit

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: combined_fit.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/shared.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -o Makefile combined_fit.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/shared.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -o Makefile combined_fit.pro

dist: 
	@$(CHK_DIR_EXISTS) objects/comb_fit1.0.0 || $(MKDIR) objects/comb_fit1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) objects/comb_fit1.0.0/ && (cd `dirname objects/comb_fit1.0.0` && $(TAR) comb_fit1.0.0.tar comb_fit1.0.0 && $(COMPRESS) comb_fit1.0.0.tar) && $(MOVE) `dirname objects/comb_fit1.0.0`/comb_fit1.0.0.tar.gz . && $(DEL_FILE) -r objects/comb_fit1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

objects/RandomNumbers.o: src/RandomNumbers.cc src/RandomNumbers.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/RandomNumbers.o src/RandomNumbers.cc

objects/GaussMutOp.o: src/GaussMutOp.cc src/RandomNumbers.h \
		src/GaussMutOp.h \
		src/MyFloatingPoint.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/GaussMutOp.o src/GaussMutOp.cc

objects/MyFloatingPoint.o: src/MyFloatingPoint.cc src/MyFloatingPoint.h \
		src/GaussMutOp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/MyFloatingPoint.o src/MyFloatingPoint.cc

objects/main.o: src/main.cpp src/MyFloatingPoint.h \
		src/GaussMutOp.h \
		src/EvalOp.h \
		src/GaussianFitFunctor.h \
		src/basis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/main.o src/main.cpp

objects/GaussianFitFunctor.o: src/GaussianFitFunctor.cpp src/GaussianFitFunctor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/GaussianFitFunctor.o src/GaussianFitFunctor.cpp

objects/EvalOp.o: src/EvalOp.cc src/EvalOp.h \
		src/GaussianFitFunctor.h \
		src/MyFloatingPoint.h \
		src/GaussMutOp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/EvalOp.o src/EvalOp.cc

objects/basis.o: src/basis.cpp src/basis.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects/basis.o src/basis.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

